"""Print the Token Factory model catalogue with prices (GET /v1/models?verbose=true).

    uv run python -m scripts.list_models                  # table of every model
    uv run python -m scripts.list_models --write-prices   # also update .env.example

Rows marked * are NVIDIA models, + are embedding models. --write-prices writes a commented
MODEL_PRICES example (NVIDIA + embedding models) into .env.example; it never touches .env.
This is a GET only: no inference, no credits spent.
"""

import argparse
import json
import re
import sys
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path
from typing import Any

import httpx

from backend.app.config import get_settings

ENV_EXAMPLE = Path(".env.example")
BLOCK_START = "# >>> MODEL_PRICES (generated by `scripts/list_models.py --write-prices`)"
BLOCK_END = "# <<< MODEL_PRICES"


@dataclass
class ModelInfo:
    id: str
    type: str  # chat | embedding | other
    context_length: int | None
    input_per_m: float | None  # USD per 1M prompt tokens
    output_per_m: float | None  # USD per 1M completion tokens
    is_nvidia: bool

    @property
    def is_embedding(self) -> bool:
        return self.type == "embedding"


def _per_million(value: Any) -> float | None:
    if value in (None, ""):
        return None
    # Prices come back per token as strings ("0.00000006"); Decimal avoids float noise.
    return float(Decimal(str(value)) * 1_000_000)


def model_type(raw: dict[str, Any]) -> str:
    modality = ((raw.get("architecture") or {}).get("modality") or "").lower()
    output = modality.split("->")[-1]
    if "embed" in output or "embed" in raw["id"].lower():
        return "embedding"
    if output == "text":
        return "chat"
    return "other"


def parse_models(payload: dict[str, Any]) -> list[ModelInfo]:
    models = []
    for raw in payload.get("data", []):
        pricing = raw.get("pricing") or {}
        text = f"{raw['id']} {raw.get('owned_by') or ''}".lower()
        models.append(
            ModelInfo(
                id=raw["id"],
                type=model_type(raw),
                context_length=raw.get("context_length"),
                input_per_m=_per_million(pricing.get("prompt")),
                output_per_m=_per_million(pricing.get("completion")),
                is_nvidia="nvidia" in text or "nemotron" in text,
            )
        )
    return sorted(models, key=lambda m: (not m.is_nvidia, not m.is_embedding, m.id.lower()))


def prices_json(models: list[ModelInfo]) -> dict[str, dict[str, float]]:
    return {
        m.id: {"input": m.input_per_m or 0.0, "output": m.output_per_m or 0.0}
        for m in models
        if (m.is_nvidia or m.is_embedding) and m.input_per_m is not None
    }


def render_block(prices: dict[str, dict[str, float]]) -> str:
    line = json.dumps(prices, separators=(", ", ": "))
    return "\n".join(
        [
            BLOCK_START,
            "# USD per 1M tokens from GET /v1/models?verbose=true. Copy into .env (uncommented).",
            f"# MODEL_PRICES={line}",
            BLOCK_END,
        ]
    )


def update_env_example(text: str, block: str) -> str:
    """Replace the generated block if present, else insert it after the MODEL_PRICES line."""
    pattern = re.compile(re.escape(BLOCK_START) + r".*?" + re.escape(BLOCK_END), re.DOTALL)
    if pattern.search(text):
        return pattern.sub(lambda _: block, text)
    anchor = re.search(r"^MODEL_PRICES=.*$", text, re.MULTILINE)
    if anchor:
        return text[: anchor.end()] + "\n" + block + text[anchor.end() :]
    return text.rstrip("\n") + "\n\n" + block + "\n"


def _fmt_price(value: float | None) -> str:
    return "?" if value is None else f"{value:.3f}"


def print_table(models: list[ModelInfo]) -> None:
    bold = sys.stdout.isatty()
    header = f"   {'model':<48} {'type':<10} {'context':>9} {'in $/1M':>8} {'out $/1M':>9}"
    print(header)
    print("   " + "-" * (len(header) - 3))
    for m in models:
        mark = "*" if m.is_nvidia else ("+" if m.is_embedding else " ")
        ctx = f"{m.context_length:,}" if m.context_length else "?"
        row = (
            f" {mark} {m.id:<48} {m.type:<10} {ctx:>9} "
            f"{_fmt_price(m.input_per_m):>8} {_fmt_price(m.output_per_m):>9}"
        )
        highlight = bold and (m.is_nvidia or m.is_embedding)
        print(f"\033[1m{row}\033[0m" if highlight else row)
    print("\n * NVIDIA model   + embedding model")


def fetch_catalogue() -> dict[str, Any]:
    settings = get_settings()
    if settings.nebius_api_key is None or not settings.nebius_api_key.get_secret_value():
        raise SystemExit("NEBIUS_API_KEY is not set. Copy .env.example to .env and add your key.")
    resp = httpx.get(
        settings.nebius_base_url.rstrip("/") + "/models",
        params={"verbose": "true"},
        headers={"Authorization": f"Bearer {settings.nebius_api_key.get_secret_value()}"},
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--write-prices",
        action="store_true",
        help="write a commented MODEL_PRICES example into .env.example (never .env)",
    )
    args = parser.parse_args()

    models = parse_models(fetch_catalogue())
    print(f"Token Factory catalogue: {len(models)} models\n")
    print_table(models)

    if args.write_prices:
        prices = prices_json(models)
        ENV_EXAMPLE.write_text(
            update_env_example(ENV_EXAMPLE.read_text(encoding="utf-8"), render_block(prices)),
            encoding="utf-8",
        )
        print(f"\nWrote MODEL_PRICES example for {len(prices)} models to {ENV_EXAMPLE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
